### PR TITLE
Make use of reusable workflow

### PR DESCRIPTION
**Pull request by mkurz**
@SethTisue We have some reusable workflows https://github.com/playframework/.github/tree/main/.github/workflows we use for every repo in the Play org. That should lower the maintenance burden.

### CODE REVIEW

**Comment by ihostage** [comment]
It's first case with Java 17 😄 It needs analyzing what happened....
https://github.com/playframework/play-webgoat/runs/6026021623?check_suite_focus=true

**Comment by mkurz** [comment]
The problem is that the jabba maintainer is not very active anymore, so the index on https://github.com/shyiko/jabba is out of date: https://github.com/shyiko/jabba/blob/master/index.json - there is no adopt 17 and not even temurin yet.
However we are lucky, there is a index that is very well maintained from typelevel we can use: https://github.com/typelevel/jdk-index
We just have to set the `JABBA_INDEX` env variable.
I will provide a pull request in a minute.

**Comment by ihostage** [comment]
Hm.... Coursier index also don't have a Adopt#17 😞 
https://github.com/coursier/jvm-index/blob/master/index.json

**Comment by mkurz** [comment]
Ah, there is an index as well. I think there we can use "adoptium" which are the temurin builds.

**Comment by ihostage** [comment]
https://get-coursier.io/docs/cli-java.html#jvm-index
> If needed, that index could be complemented or replaced by [an index of our own](https://github.com/coursier/jvm-index) at some point.

Courier index isn't default, as I understand. It's just an alternative like same the index from Typelevel.

**Comment by mkurz** [comment]
Hmm... https://github.com/coursier/jvm-index#use-by-coursier:
> The index generated here is now used by the `java` and `java-home` commands of [coursier](https://get-coursier.io/).

I will just try, if not I will explicitly set the index.

**Comment by ihostage** [comment]
May be it's only for `2.1.0-M*` versions 🤔 But we use the `2.0.16`.

**Comment by mkurz** [comment]
OK, I found the problem.
https://github.com/playframework/play-webgoat/runs/6026468773?check_suite_focus=true#step:6:13
```
/opt/hostedtoolcache/cs/2.0.16/x64/cs java --jvm adoptium:17 -version
```
Our workflow uses cs 2.0.16, which still uses the jabba index.
Starting with cs 2.1.0-M1 (https://github.com/coursier/coursier/releases/tag/v2.1.0-M1) they switched to to their own index: https://github.com/coursier/coursier/pull/2205
Also see [this commit](https://github.com/coursier/jvm-index/commit/4addf155310f78e8690b1fe70062e818eab2c5e7) where they changed the wording from

> The index generated here *could* be used...

to

> The index generated here *is used*...


So it looks like the docs you linked for 2.1.0-M... is out of date (https://get-coursier.io/docs/cli-java.html#jvm-index).

**Comment by mkurz** [comment]
Your were 5 seconds faster :wink: 
So we have to use the index explictly until the action uses cs 2.1.0

**Comment by ihostage** [comment]
> So we have to use the index explictly until the action uses cs 2.1.0

It's already, but only for pre-release versions.
https://github.com/coursier/setup-action/releases/tag/v1.2.0-M3

We can use a milestone version of action that use a milestone of coursier. But I'm not sure that it's a good idea. 😄

**Comment by mkurz** [comment]
I think it should be fine to use the -M3, since cs is "just" used to install java or not? Anyway, I will continue after dinner

**Comment by mkurz** [comment]
You can of course continue if you have free time ;)

**Review by ihostage — APPROVED** [review]

**Pull request merged**
