### PR TITLE
[WIP]: Gradle support

### PR DESCRIPTION
**Pull request by marcospereira**
# WIP DO NOT MERGE

Let me first figure it out if Fortify is running when compiling code using Gradle.

---------

Add `build.gradle`, including Fortify configuration as described here: https://developer.lightbend.com/docs/fortify/latest/#getting-and-using-the-translator-with-gradle-

### CODE REVIEW

**Comment by SethTisue** [comment]
```
A problem occurred evaluating root project 'play-webgoat'.
> Could not get unknown property 'lightbendUser' for Credentials [username: null] of type org.gradle.api.internal.artifacts.repositories.DefaultPasswordCredentials_Decorated.
```

**Comment by marcospereira** [comment]
@SethTisue just saw it.

We either need to configure [encrypted crendentials](https://docs.travis-ci.com/user/encryption-keys/) (and if so, which ones?) or not have Fortify configured here.

**Comment by SethTisue** [comment]
there is a `fortify` branch of this repo, where I removed the `.travis.yml` file since we haven't done the encrypted-credentials thing

perhaps we should rename the `fortify` branch to `fortify-sbt` and add a `fortify-gradle` branch

**Comment by marcospereira** [comment]
@SethTisue makes sense to me.

I can't do it right now but will take a look at it later. :-)

**Comment by octonato** [comment]
This won't work with TemplateControl, because it expects the branches to be 2.5.x, 2.6.x or 2.7.x

The current `fortify` branch won't be updated by TC for instance. 

However, we have faced many issues with TC in the last month and we have a few ideas on how to improve it. We may consider make it more flexible.

**Comment by dwijnand** [comment]
Probably best to just get fortify working on the 2.6.x and 2.7.x branches.

**Comment by SethTisue** [comment]
it's no big deal for me to keep the `fortify` branch updated myself, I just merge from an upstream branch from time to time, whenever a new Scala version comes out or a new Fortify plugin version comes out..

as for testing the `fortify` branch, that's now handled by https://ci.lightbend.com/view/Fortify/job/play-webgoat/

I'm not sure why I suggested having separate `fortify-sbt` and `fortify-gradle` branches, seems like it would be fine to have both builds on the same branch..

**Comment by dwijnand** [comment]
OK, then let's tear out the fortify things from this PR and land it.

**Comment by SethTisue** [comment]
needs rebase

**Pull request closed without merging**
